// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZ_6ui_ncomjm6-DnLucJY-VOPFLBAqM',
    appId: '1:131411445819:web:86120c7cb030c877fd341e',
    messagingSenderId: '131411445819',
    projectId: 'plant-nursery-app',
    authDomain: 'plant-nursery-app.firebaseapp.com',
    storageBucket: 'plant-nursery-app.appspot.com',
    measurementId: 'G-RF7HDQ4KEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZxEkYkl6WpGAlM0oF4gL1OkyreXPA--8',
    appId: '1:131411445819:android:82b62714e8b3f6b6fd341e',
    messagingSenderId: '131411445819',
    projectId: 'plant-nursery-app',
    storageBucket: 'plant-nursery-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARwkjayAD7nnRHG9gySa7Ti9Q1KUXZ03g',
    appId: '1:131411445819:ios:f4304e137463a965fd341e',
    messagingSenderId: '131411445819',
    projectId: 'plant-nursery-app',
    storageBucket: 'plant-nursery-app.appspot.com',
    iosBundleId: 'com.example.plantNuseryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARwkjayAD7nnRHG9gySa7Ti9Q1KUXZ03g',
    appId: '1:131411445819:ios:f4304e137463a965fd341e',
    messagingSenderId: '131411445819',
    projectId: 'plant-nursery-app',
    storageBucket: 'plant-nursery-app.appspot.com',
    iosBundleId: 'com.example.plantNuseryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQZ_6ui_ncomjm6-DnLucJY-VOPFLBAqM',
    appId: '1:131411445819:web:188d4e19186e723ffd341e',
    messagingSenderId: '131411445819',
    projectId: 'plant-nursery-app',
    authDomain: 'plant-nursery-app.firebaseapp.com',
    storageBucket: 'plant-nursery-app.appspot.com',
    measurementId: 'G-CNQX9NVPZ6',
  );
}
